/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    courses: Course;
    universities: University;
    'success-stories': SuccessStory;
    applications: Application;
    'form-submissions': FormSubmission;
    testimonials: Testimonial;
    'blog-posts': BlogPost;
    'service-packages': ServicePackage;
    'newsletter-subscribers': NewsletterSubscriber;
    'newsletter-campaigns': NewsletterCampaign;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    universities: UniversitiesSelect<false> | UniversitiesSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'service-packages': ServicePackagesSelect<false> | ServicePackagesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'newsletter-campaigns': NewsletterCampaignsSelect<false> | NewsletterCampaignsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  /**
   * Arama motoru optimizasyonu ayarları
   */
  seo?: {
    /**
     * İçeriğin hedeflediği ana anahtar kelime. SEO puanı buna göre hesaplanır.
     */
    focusKeyword?: string | null;
    /**
     * Arama sonuçlarında görünecek başlık. 50-60 karakter ideal.
     */
    metaTitle?: string | null;
    /**
     * Arama sonuçlarında görünecek açıklama. 120-160 karakter ideal.
     */
    metaDescription?: string | null;
  };
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  programType: 'studienkolleg' | 'bachelor' | 'master' | 'ausbildung' | 'language';
  field?:
    | (
        | 'engineering'
        | 'medicine'
        | 'business'
        | 'cs'
        | 'law'
        | 'science'
        | 'social-science'
        | 'art'
        | 'architecture'
        | 'other'
      )
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  image?: (number | null) | Media;
  language?: ('de' | 'en' | 'de-en') | null;
  /**
   * Örn: 1 Yıl, 3-4 Yıl, 6 Ay, 2 Yıl
   */
  duration?: string | null;
  germanLevel?: ('none' | 'a1' | 'a2' | 'b1' | 'b2' | 'c1' | 'c2') | null;
  /**
   * Örn: Devlet üniversiteleri ücretsiz, sadece semesterbeitrag (~300€/dönem)
   */
  tuitionInfo?: string | null;
  requirements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Örn: Kış dönemi: 15 Temmuz, Yaz dönemi: 15 Ocak
   */
  applicationDeadline?: string | null;
  relatedUniversities?: (number | University)[] | null;
  status?: ('active' | 'upcoming' | 'inactive') | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * Arama motoru optimizasyonu ayarları
   */
  seo?: {
    /**
     * İçeriğin hedeflediği ana anahtar kelime. SEO puanı buna göre hesaplanır.
     */
    focusKeyword?: string | null;
    /**
     * Arama sonuçlarında görünecek başlık. 50-60 karakter ideal.
     */
    metaTitle?: string | null;
    /**
     * Arama sonuçlarında görünecek açıklama. 120-160 karakter ideal.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities".
 */
export interface University {
  id: number;
  name: string;
  slug: string;
  logo?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  city: string;
  bundesland?:
    | (
        | 'baden-wuerttemberg'
        | 'bayern'
        | 'berlin'
        | 'brandenburg'
        | 'bremen'
        | 'hamburg'
        | 'hessen'
        | 'mecklenburg-vorpommern'
        | 'niedersachsen'
        | 'nordrhein-westfalen'
        | 'rheinland-pfalz'
        | 'saarland'
        | 'sachsen'
        | 'sachsen-anhalt'
        | 'schleswig-holstein'
        | 'thueringen'
      )
    | null;
  type?: ('public-uni' | 'tu' | 'fh' | 'private' | 'art') | null;
  founded?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  websiteUrl?: string | null;
  ranking?: {
    qsWorld?: number | null;
    theWorld?: number | null;
  };
  stats?: {
    totalStudents?: number | null;
    internationalPercent?: number | null;
    /**
     * Örn: ~310€/dönem
     */
    semesterFee?: string | null;
  };
  /**
   * Üniversite şartlı kabul veriyor mu?
   */
  conditionalAcceptance?: ('yes' | 'no' | 'unknown') | null;
  /**
   * Şartlı kabul için minimum Almanca seviyesi
   */
  conditionalAcceptanceLevel?: ('none' | 'a1' | 'a2' | 'b1' | 'b2' | 'c1') | null;
  /**
   * Bu üniversitede Studienkolleg var mı?
   */
  studienkolleg?: boolean | null;
  applicationDeadlines?: {
    /**
     * Örn: 15 Temmuz
     */
    winterSemester?: string | null;
    /**
     * Örn: 15 Ocak
     */
    summerSemester?: string | null;
  };
  programs?:
    | {
        name: string;
        degree?: ('bachelor' | 'master') | null;
        language?: ('de' | 'en' | 'de-en') | null;
        id?: string | null;
      }[]
    | null;
  isPartner?: boolean | null;
  sortOrder?: number | null;
  /**
   * Arama motoru optimizasyonu ayarları
   */
  seo?: {
    /**
     * İçeriğin hedeflediği ana anahtar kelime. SEO puanı buna göre hesaplanır.
     */
    focusKeyword?: string | null;
    /**
     * Arama sonuçlarında görünecek başlık. 50-60 karakter ideal.
     */
    metaTitle?: string | null;
    /**
     * Arama sonuçlarında görünecek açıklama. 120-160 karakter ideal.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  studentName: string;
  photo?: (number | null) | Media;
  university?: (number | null) | University;
  /**
   * Üniversite listede yoksa buraya yazın
   */
  universityName?: string | null;
  program: string;
  programType?: ('studienkolleg' | 'bachelor' | 'master' | 'ausbildung' | 'language') | null;
  city?: string | null;
  year: number;
  testimonial: string;
  videoUrl?: string | null;
  rating?: number | null;
  isParentTestimonial?: boolean | null;
  featured?: boolean | null;
  isActive?: boolean | null;
  /**
   * Arama motoru optimizasyonu ayarları
   */
  seo?: {
    /**
     * İçeriğin hedeflediği ana anahtar kelime. SEO puanı buna göre hesaplanır.
     */
    focusKeyword?: string | null;
    /**
     * Arama sonuçlarında görünecek başlık. 50-60 karakter ideal.
     */
    metaTitle?: string | null;
    /**
     * Arama sonuçlarında görünecek açıklama. 120-160 karakter ideal.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  fullName: string;
  email: string;
  phone: string;
  whatsapp?: string | null;
  currentEducation?:
    | ('high-school-regular' | 'high-school-open' | 'university' | 'bachelor-grad' | 'master-grad' | 'working')
    | null;
  programType: 'studienkolleg' | 'bachelor' | 'master' | 'ausbildung' | 'language' | 'undecided';
  fieldOfStudy?: string | null;
  germanLevel?: ('none' | 'a1' | 'a2' | 'b1' | 'b2' | 'c1' | 'c2') | null;
  preferredSemester?: ('winter' | 'summer' | 'asap') | null;
  budget?: ('scholarship' | 'under-10k' | '10k-20k' | 'over-20k') | null;
  message?: string | null;
  source?: ('google' | 'instagram' | 'youtube' | 'referral' | 'event' | 'other') | null;
  status?:
    | ('new' | 'contacted' | 'consulting' | 'documents' | 'applied' | 'accepted' | 'visa' | 'enrolled' | 'cancelled')
    | null;
  assignedTo?: (number | null) | User;
  notes?:
    | {
        date: string;
        note: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  /**
   * Formun gönderildiği sayfa
   */
  source?: string | null;
  status?: ('new' | 'read' | 'replied' | 'closed') | null;
  assignedTo?: (number | null) | User;
  notes?:
    | {
        date: string;
        note: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  role?: string | null;
  content: string;
  rating?: number | null;
  avatar?: (number | null) | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Blog yazısının tam içeriği. Markdown formatında yazabilirsiniz.
   */
  markdownBody?: string | null;
  featuredImage?: (number | null) | Media;
  category?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  /**
   * Arama motoru optimizasyonu ayarları
   */
  seo?: {
    /**
     * İçeriğin hedeflediği ana anahtar kelime. SEO puanı buna göre hesaplanır.
     */
    focusKeyword?: string | null;
    /**
     * Arama sonuçlarında görünecek başlık. 50-60 karakter ideal.
     */
    metaTitle?: string | null;
    /**
     * Arama sonuçlarında görünecek açıklama. 120-160 karakter ideal.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-packages".
 */
export interface ServicePackage {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Sayısal değer (örn: 1000)
   */
  price: number;
  currency?: ('EUR' | 'TRY') | null;
  /**
   * Karşılaştırma tablosunda gösterilecek özellikler. Değer alanına 'Dahil', 'Dahil değil' veya özel metin yazabilirsiniz.
   */
  features?:
    | {
        featureName: string;
        /**
         * Örn: Dahil, Dahil değil, 1, 3, %100, Anlaşmalı dil kursu
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Kart görünümünde gösterilecek kısa özellik listesi
   */
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Örn: Yeminli tercüme ve başvuru masrafları pakete dahildir.
   */
  note?: string | null;
  ctaText?: string | null;
  popular?: boolean | null;
  sortOrder?: number | null;
  status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter aboneleri
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  name?: string | null;
  status?: ('active' | 'unsubscribed' | 'bounced') | null;
  subscribedAt?: string | null;
  unsubscribedAt?: string | null;
  unsubscribeToken?: string | null;
  source?: ('blog' | 'homepage' | 'footer' | 'popup' | 'manual') | null;
  /**
   * Abone segmentasyonu için etiketler
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter kampanyaları oluşturun ve gönderin
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-campaigns".
 */
export interface NewsletterCampaign {
  id: number;
  /**
   * İç kullanım için kampanya adı (abone görmez)
   */
  name: string;
  /**
   * Abonelerin göreceği e-posta başlığı
   */
  subject: string;
  /**
   * E-posta istemcisinde konu satırının yanında görünen kısa metin
   */
  previewText?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * HTML desteklemeyen e-posta istemcileri için düz metin versiyonu
   */
  plainTextContent?: string | null;
  status?: ('draft' | 'ready' | 'sending' | 'sent' | 'failed') | null;
  targetAudience?: ('all' | 'by-tags') | null;
  /**
   * Bu etiketlere sahip abonelere gönderilecek
   */
  targetTags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Boş bırakılırsa, durumu 'Gönderime Hazır' yapıldığında anında gönderilir
   */
  scheduledAt?: string | null;
  sentAt?: string | null;
  recipientCount?: number | null;
  successCount?: number | null;
  failCount?: number | null;
  errorLog?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'universities';
        value: number | University;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'service-packages';
        value: number | ServicePackage;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'newsletter-campaigns';
        value: number | NewsletterCampaign;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  featuredImage?: T;
  seo?:
    | T
    | {
        focusKeyword?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  programType?: T;
  field?: T;
  description?: T;
  shortDescription?: T;
  image?: T;
  language?: T;
  duration?: T;
  germanLevel?: T;
  tuitionInfo?: T;
  requirements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  applicationDeadline?: T;
  relatedUniversities?: T;
  status?: T;
  featured?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        focusKeyword?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "universities_select".
 */
export interface UniversitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  coverImage?: T;
  city?: T;
  bundesland?: T;
  type?: T;
  founded?: T;
  description?: T;
  shortDescription?: T;
  websiteUrl?: T;
  ranking?:
    | T
    | {
        qsWorld?: T;
        theWorld?: T;
      };
  stats?:
    | T
    | {
        totalStudents?: T;
        internationalPercent?: T;
        semesterFee?: T;
      };
  conditionalAcceptance?: T;
  conditionalAcceptanceLevel?: T;
  studienkolleg?: T;
  applicationDeadlines?:
    | T
    | {
        winterSemester?: T;
        summerSemester?: T;
      };
  programs?:
    | T
    | {
        name?: T;
        degree?: T;
        language?: T;
        id?: T;
      };
  isPartner?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        focusKeyword?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  studentName?: T;
  photo?: T;
  university?: T;
  universityName?: T;
  program?: T;
  programType?: T;
  city?: T;
  year?: T;
  testimonial?: T;
  videoUrl?: T;
  rating?: T;
  isParentTestimonial?: T;
  featured?: T;
  isActive?: T;
  seo?:
    | T
    | {
        focusKeyword?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  currentEducation?: T;
  programType?: T;
  fieldOfStudy?: T;
  germanLevel?: T;
  preferredSemester?: T;
  budget?: T;
  message?: T;
  source?: T;
  status?: T;
  assignedTo?: T;
  notes?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  source?: T;
  status?: T;
  assignedTo?: T;
  notes?:
    | T
    | {
        date?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  role?: T;
  content?: T;
  rating?: T;
  avatar?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  markdownBody?: T;
  featuredImage?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  publishedAt?: T;
  status?: T;
  seo?:
    | T
    | {
        focusKeyword?: T;
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-packages_select".
 */
export interface ServicePackagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  currency?: T;
  features?:
    | T
    | {
        featureName?: T;
        value?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  note?: T;
  ctaText?: T;
  popular?: T;
  sortOrder?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  status?: T;
  subscribedAt?: T;
  unsubscribedAt?: T;
  unsubscribeToken?: T;
  source?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-campaigns_select".
 */
export interface NewsletterCampaignsSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  previewText?: T;
  content?: T;
  plainTextContent?: T;
  status?: T;
  targetAudience?: T;
  targetTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  scheduledAt?: T;
  sentAt?: T;
  recipientCount?: T;
  successCount?: T;
  failCount?: T;
  errorLog?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    whatsapp?: string | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
  };
  seo?: {
    /**
     * Örn: %s | Firma Adı (%s sayfa başlığının yerini alır)
     */
    titleTemplate?: string | null;
    defaultDescription?: string | null;
  };
  analytics?: {
    /**
     * Örn: G-XXXXXXXXXX
     */
    gaId?: string | null;
    /**
     * Örn: GTM-XXXXXXX
     */
    gtmId?: string | null;
    /**
     * google-site-verification meta tag değeri
     */
    searchConsoleId?: string | null;
  };
  businessHours?:
    | {
        day: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  googleMapsEmbed?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        whatsapp?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        twitter?: T;
        youtube?: T;
        linkedin?: T;
        tiktok?: T;
      };
  seo?:
    | T
    | {
        titleTemplate?: T;
        defaultDescription?: T;
      };
  analytics?:
    | T
    | {
        gaId?: T;
        gtmId?: T;
        searchConsoleId?: T;
      };
  businessHours?:
    | T
    | {
        day?: T;
        hours?: T;
        id?: T;
      };
  googleMapsEmbed?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}